// Generated by gen_sram_macros.py — black-box stub for synthesis.
(* blackbox *)
module mobol_sram_4096x512_2r1w
(
   rd0_out,
   rd1_out,
   raddr0_in,
   raddr1_in,
   waddr_in,
   wd_in,
   we_in,
   clk,
   ce_in
);
   output [511:0] rd0_out;
   output [511:0] rd1_out;
   input  [11:0] raddr0_in;
   input  [11:0] raddr1_in;
   input  [11:0] waddr_in;
   input  [511:0] wd_in;
   input  we_in;
   input  clk;
   input  ce_in;
endmodule
