// Generated by gen_sram_macros.py (FakeRAM2.0 extended: 2R1W)
// Behavioral model — NOT for synthesis (use mobol_sram_4096x512_2r1w.bb.v + .lib/.lef).
module mobol_sram_4096x512_2r1w
(
   rd0_out,
   rd1_out,
   raddr0_in,
   raddr1_in,
   waddr_in,
   wd_in,
   we_in,
   clk,
   ce_in
);
   parameter BITS = 512;
   parameter WORD_DEPTH = 4096;
   parameter ADDR_WIDTH = 12;

   output reg [511:0] rd0_out;
   output reg [511:0] rd1_out;
   input      [11:0] raddr0_in;
   input      [11:0] raddr1_in;
   input      [11:0] waddr_in;
   input      [511:0] wd_in;
   input              we_in;
   input              clk;
   input              ce_in;

   reg [BITS-1:0] mem [0:WORD_DEPTH-1];

   // Write and both reads are clocked together: a read of the address
   // being written this cycle returns the OLD value (non-blocking order),
   // matching the RTL behavioral model rtl/sram/sram_2r1w.sv.
   always @(posedge clk) begin
      if (ce_in) begin
         if (we_in) mem[waddr_in] <= wd_in;
         rd0_out <= mem[raddr0_in];
         rd1_out <= mem[raddr1_in];
      end
   end
endmodule
