#!/usr/bin/env python3
"""gen_sram_macros.py — batch-generate SRAM macro views for the MOBOL RTL.

What it does
------------
1. Writes a FakeRAM2.0 config (`mobol_sram.cfg`) whose process section is
   derived from the USC-3N-2D PDK (3 nm GAA, M4 pin layer, 36 nm pitch).
2. Runs stock FakeRAM2.0 (`run.py`) to generate the plain 1RW macro views
   (Liberty / LEF / Verilog) — kept as a reference and for any future 1RW use.
3. Emits *extended 2R1W views* for the macros the RTL actually needs
   (ARCH_SPEC §3.5: LOCAL scratchpad is 2-read + 1-write, 64 B/port).
   FakeRAM2.0 hardcodes `rw_ports = 1`, so this script reuses FakeRAM2.0's
   Process + area model and writes the multi-port .lib/.lef/.v/.bb.v itself,
   with the same Liberty structure and dummy timing numbers FakeRAM2.0 uses.
   Area model: 2R1W is costed as 2x the 1RW bitcell array (dual-copy
   replication — exactly how real memory compilers build 2R1W from 6T/8T).
4. Patches the stock FakeRAM2.0 behavioral Verilog write bug
   (`mem[addr] <= wd | mem[addr]` — a leftover of the removed write mask).

Usage
-----
    python3 gen_sram_macros.py [--fakeram /path/to/FakeRAM2.0]
                               [--out /path/to/output_dir]

Outputs (per macro, under --out, default ../macros):
    <name>/<name>.lib     Liberty timing view (for Yosys/OpenSTA/OpenROAD)
    <name>/<name>.lef     physical abstract (for OpenROAD)
    <name>/<name>.v       behavioral model (simulation)
    <name>/<name>.bb.v    black-box stub (Yosys synthesis)
"""

import argparse
import math
import re
import subprocess
import sys
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────
# Process description for USC-3N-2D (SCCAD 3 nm GAA, front-side PDN).
#   - metal_layer M4:   pin layer; tech LEF: PITCH 0.036, WIDTH 0.018
#   - manufacturing grid: PDK is 0.1 nm; FakeRAM wants an integer nm, and
#     1 nm is a legal (coarser) multiple, so all coordinates stay on grid.
#   - contacted_poly_pitch / fin_pitch: bitcell-size knobs of FakeRAM's
#     area model (bitcell = 2*CPP x 10*fin_pitch). 48/24 nm give a
#     0.096 x 0.24 um bitcell ≈ 0.023 um² — a plausible N3 HD SRAM cell.
# ──────────────────────────────────────────────────────────────────────────
PROCESS_CFG = {
    "tech_nm": 3,
    "voltage": 0.7,                  # PDK lib nom_voltage
    "metal_prefix": "M",
    "metal_layer": "M4",
    "pin_width_nm": 18,
    "pin_pitch_nm": 36,
    "metal_track_pitch_nm": 36,
    "manufacturing_grid_nm": 1,
    "contacted_poly_pitch_nm": 48,
    "fin_pitch_nm": 24,
    "column_mux_factor": 1,
}

# One physical geometry serves the whole chip (ARCH_SPEC §3.5 + §6.1):
#   LOCAL scratchpad : 256 KB/tile = 4096 lines x 512 b  -> 1 macro/tile
#   SHARED bank      : 8 MB/bank   = 32 x (4096 x 512 b) -> 32 macros/bank
# depth 4096 / banks 4 keeps the macro near-square (~236 x ~295 um).
SRAMS_1RW = [
    {"name": "mobol_sram_4096x512_1rw", "width": 512, "depth": 4096, "banks": 4},
]
SRAMS_2R1W = [
    {"name": "mobol_sram_4096x512_2r1w", "width": 512, "depth": 4096, "banks": 4},
]

MULTIPORT_AREA_FACTOR = 2.0   # 2R1W = dual-copy of the 1RW array


# ──────────────────────────────────────────────────────────────────────────
# 2R1W Verilog views
# ──────────────────────────────────────────────────────────────────────────
def ports_2r1w(bits, aw):
    """(name, direction, width) for every pin of the 2R1W macro."""
    return [
        ("rd0_out",   "output", bits), ("rd1_out",   "output", bits),
        ("raddr0_in", "input",  aw),   ("raddr1_in", "input",  aw),
        ("waddr_in",  "input",  aw),   ("wd_in",     "input",  bits),
        ("we_in",     "input",  1),
        ("clk",       "input",  1),    ("ce_in",     "input",  1),
    ]


def write_verilog_2r1w(mem, out_dir):
    """Behavioral model. Semantics match rtl/sram/sram_2r1w.sv exactly when
    ce_in==1: synchronous write + synchronous read (1-cycle latency),
    read-during-write to the same address returns the OLD data."""
    bits, aw = mem["width"], int(math.log2(mem["depth"]))
    decls = "\n".join(
        f"   {'output reg' if d == 'output' else 'input     '} "
        f"{f'[{w-1}:0] ' if w > 1 else '        '}{n};"
        for n, d, w in ports_2r1w(bits, aw))
    plist = ",\n   ".join(n for n, _, _ in ports_2r1w(bits, aw))
    (out_dir / f"{mem['name']}.v").write_text(f"""\
// Generated by gen_sram_macros.py (FakeRAM2.0 extended: 2R1W)
// Behavioral model — NOT for synthesis (use {mem['name']}.bb.v + .lib/.lef).
module {mem['name']}
(
   {plist}
);
   parameter BITS = {bits};
   parameter WORD_DEPTH = {mem['depth']};
   parameter ADDR_WIDTH = {aw};

{decls}

   reg [BITS-1:0] mem [0:WORD_DEPTH-1];

   // Write and both reads are clocked together: a read of the address
   // being written this cycle returns the OLD value (non-blocking order),
   // matching the RTL behavioral model rtl/sram/sram_2r1w.sv.
   always @(posedge clk) begin
      if (ce_in) begin
         if (we_in) mem[waddr_in] <= wd_in;
         rd0_out <= mem[raddr0_in];
         rd1_out <= mem[raddr1_in];
      end
   end
endmodule
""")


def write_blackbox_2r1w(mem, out_dir):
    bits, aw = mem["width"], int(math.log2(mem["depth"]))
    decls = "\n".join(
        f"   {'output' if d == 'output' else 'input '} "
        f"{f'[{w-1}:0] ' if w > 1 else ''}{n};"
        for n, d, w in ports_2r1w(bits, aw))
    plist = ",\n   ".join(n for n, _, _ in ports_2r1w(bits, aw))
    (out_dir / f"{mem['name']}.bb.v").write_text(f"""\
// Generated by gen_sram_macros.py — black-box stub for synthesis.
(* blackbox *)
module {mem['name']}
(
   {plist}
);
{decls}
endmodule
""")


# ──────────────────────────────────────────────────────────────────────────
# 2R1W Liberty view (same structure & placeholder numbers as FakeRAM2.0)
# ──────────────────────────────────────────────────────────────────────────
def _lib_out_bus(name, mem, tcq, slews, loads, min_slew, max_slew, raddr):
    m = mem["name"]
    return f"""\
    bus({name})   {{
        bus_type : {m}_DATA;
        direction : output;
        max_capacitance : {loads.split(', ')[1]};
        memory_read() {{ address : {raddr}; }}
        timing() {{
            related_pin : "clk" ;
            timing_type : rising_edge;
            timing_sense : non_unate;
            cell_rise({m}_mem_out_delay_template) {{
                index_1 ("{slews}"); index_2 ("{loads}");
                values ("{tcq}, {tcq}", "{tcq}, {tcq}")
            }}
            cell_fall({m}_mem_out_delay_template) {{
                index_1 ("{slews}"); index_2 ("{loads}");
                values ("{tcq}, {tcq}", "{tcq}, {tcq}")
            }}
            rise_transition({m}_mem_out_slew_template) {{
                index_1 ("{loads}"); values ("{min_slew}, {max_slew}")
            }}
            fall_transition({m}_mem_out_slew_template) {{
                index_1 ("{loads}"); values ("{min_slew}, {max_slew}")
            }}
        }}
    }}
"""


def _lib_in_constraints(mem, tsu, thold, slews):
    """setup/hold timing() blocks shared by every input pin/bus."""
    m = mem["name"]
    return f"""\
        timing() {{
            related_pin : clk; timing_type : setup_rising ;
            rise_constraint({m}_constraint_template) {{
                index_1 ("{slews}"); index_2 ("{slews}");
                values ("{tsu}, {tsu}", "{tsu}, {tsu}")
            }}
            fall_constraint({m}_constraint_template) {{
                index_1 ("{slews}"); index_2 ("{slews}");
                values ("{tsu}, {tsu}", "{tsu}, {tsu}")
            }}
        }}
        timing() {{
            related_pin : clk; timing_type : hold_rising ;
            rise_constraint({m}_constraint_template) {{
                index_1 ("{slews}"); index_2 ("{slews}");
                values ("{thold}, {thold}", "{thold}, {thold}")
            }}
            fall_constraint({m}_constraint_template) {{
                index_1 ("{slews}"); index_2 ("{slews}");
                values ("{thold}, {thold}", "{thold}, {thold}")
            }}
        }}
"""


def write_lib_2r1w(mem, dims, out_dir, voltage):
    """Liberty view. Numbers below are FakeRAM2.0's placeholder values
    (class_memory.py); replace with silicon/compiler data when available."""
    name = mem["name"]
    bits, aw = mem["width"], int(math.log2(mem["depth"]))
    w_um, h_um, area = dims
    # FakeRAM2.0 placeholder timing/power (see utils/class_memory.py)
    tcq, tsu, thold = 0.2183, 0.050, 0.050        # ns
    min_period = 0.1566                            # ns
    leakage = 0.1289e3                             # uW
    cap_in = 0.005                                 # pF
    fo4 = 9.0632e-3                                # ns
    min_slew, max_slew = 1 * fo4, 25 * fo4
    min_load, max_load = 1 * cap_in, 100 * cap_in
    slews = f"{min_slew:.3f}, {max_slew:.3f}"
    loads = f"{min_load:.3f}, {max_load:.3f}"
    f = lambda v: f"{v:.3f}"

    hdr = f"""\
library({name}) {{
    technology (cmos);
    delay_model : table_lookup;
    revision : 1.0;
    comment : "MOBOL 2R1W SRAM (FakeRAM2.0-extended placeholder timing)";
    time_unit : "1ns";
    voltage_unit : "1V";
    current_unit : "1uA";
    leakage_power_unit : "1uW";
    nom_process : 1;
    nom_temperature : 25.000;
    nom_voltage : {voltage};
    capacitive_load_unit (1,pf);
    pulling_resistance_unit : "1kohm";
    operating_conditions(tt_{voltage}_25.0) {{
        process : 1; temperature : 25.000; voltage : {voltage};
        tree_type : balanced_tree;
    }}
    default_operating_conditions : tt_{voltage}_25.0;
    default_cell_leakage_power : 0;
    default_fanout_load : 1;
    default_inout_pin_cap : 0.0;
    default_input_pin_cap : 0.0;
    default_output_pin_cap : 0.0;
    default_max_transition : {f(max_slew)};
    slew_derate_from_library : 1.000;
    slew_lower_threshold_pct_fall : 20.000;
    slew_upper_threshold_pct_fall : 80.000;
    slew_lower_threshold_pct_rise : 20.000;
    slew_upper_threshold_pct_rise : 80.000;
    input_threshold_pct_fall : 50.000;
    input_threshold_pct_rise : 50.000;
    output_threshold_pct_fall : 50.000;
    output_threshold_pct_rise : 50.000;
    lu_table_template({name}_mem_out_delay_template) {{
        variable_1 : input_net_transition;
        variable_2 : total_output_net_capacitance;
        index_1 ("1000, 1001"); index_2 ("1000, 1001");
    }}
    lu_table_template({name}_mem_out_slew_template) {{
        variable_1 : total_output_net_capacitance;
        index_1 ("1000, 1001");
    }}
    lu_table_template({name}_constraint_template) {{
        variable_1 : related_pin_transition;
        variable_2 : constrained_pin_transition;
        index_1 ("1000, 1001"); index_2 ("1000, 1001");
    }}
    library_features(report_delay_calculation);
    type ({name}_DATA) {{
        base_type : array ; data_type : bit ;
        bit_width : {bits}; bit_from : {bits-1}; bit_to : 0 ; downto : true ;
    }}
    type ({name}_ADDRESS) {{
        base_type : array ; data_type : bit ;
        bit_width : {aw}; bit_from : {aw-1}; bit_to : 0 ; downto : true ;
    }}
"""

    cell = [f"""\
cell({name}) {{
    area : {area:.3f};
    interface_timing : true;
    memory() {{
        type : ram;
        address_width : {aw};
        word_width : {bits};
    }}
    pin(clk) {{
        direction : input;
        capacitance : {f(cap_in*5)};
        clock : true;
        min_period : {f(min_period)} ;
    }}
"""]
    # read ports
    cell.append(_lib_out_bus("rd0_out", mem, f(tcq), slews, loads,
                             f(min_slew), f(max_slew), "raddr0_in"))
    cell.append(_lib_out_bus("rd1_out", mem, f(tcq), slews, loads,
                             f(min_slew), f(max_slew), "raddr1_in"))
    # input address buses
    for bus in ("raddr0_in", "raddr1_in", "waddr_in"):
        cell.append(f"""\
    bus({bus})   {{
        bus_type : {name}_ADDRESS;
        direction : input;
        capacitance : {f(cap_in)};
{_lib_in_constraints(mem, f(tsu), f(thold), slews)}\
    }}
""")
    # write data bus
    cell.append(f"""\
    bus(wd_in)   {{
        bus_type : {name}_DATA;
        memory_write() {{ address : waddr_in; clocked_on : "clk"; }}
        direction : input;
        capacitance : {f(cap_in)};
{_lib_in_constraints(mem, f(tsu), f(thold), slews)}\
    }}
""")
    # control pins
    for pin in ("we_in", "ce_in"):
        cell.append(f"""\
    pin({pin}) {{
        direction : input;
        capacitance : {f(cap_in)};
{_lib_in_constraints(mem, f(tsu), f(thold), slews)}\
    }}
""")
    cell.append(f"    cell_leakage_power : {leakage:.3f};\n}}\n}}\n")
    (out_dir / f"{name}.lib").write_text(hdr + "".join(cell))


# ──────────────────────────────────────────────────────────────────────────
# 2R1W LEF view (same pin-placement algorithm as FakeRAM2.0 create_lef)
# ──────────────────────────────────────────────────────────────────────────
def write_lef_2r1w(mem, dims, out_dir, proc):
    name = mem["name"]
    bits, aw = mem["width"], int(math.log2(mem["depth"]))
    w, h, _ = dims
    pin_w = proc["pin_width_nm"] / 1000.0
    pin_p = proc["pin_pitch_nm"] / 1000.0
    layer = proc["metal_layer"]
    prefix = proc["metal_prefix"]

    # left-edge pin column: 2 data out + 1 data in + 3 addr + we/ce/clk
    pins = ([("rd0_out", "OUTPUT", bits), ("rd1_out", "OUTPUT", bits),
             ("wd_in", "INPUT", bits),
             ("raddr0_in", "INPUT", aw), ("raddr1_in", "INPUT", aw),
             ("waddr_in", "INPUT", aw),
             ("we_in", "INPUT", 1), ("ce_in", "INPUT", 1),
             ("clk", "INPUT", 1)])
    n_pins = sum(n for _, _, n in pins)
    x_off = y_off = pin_p
    tracks = math.floor((h - 2 * y_off) / pin_p)
    if tracks < n_pins:
        sys.exit(f"error: {name}: {n_pins} pins > {tracks} tracks on edge")
    spread = max(1, tracks // n_pins)      # spread pins over spare tracks
    pitch = pin_p * spread

    out = [f"""\
# Generated by gen_sram_macros.py (FakeRAM2.0 extended: 2R1W)
VERSION 5.7 ;
BUSBITCHARS "[]" ;
MACRO {name}
  FOREIGN {name} 0 0 ;
  SYMMETRY X Y R90 ;
  SIZE {w:.3f} BY {h:.3f} ;
  CLASS BLOCK ;
"""]
    y = y_off + pin_w / 2.0
    for pname, direction, width in pins:
        for i in range(width):
            full = f"{pname}[{i}]" if width > 1 else pname
            out.append(f"""\
  PIN {full}
    DIRECTION {direction} ;
    USE SIGNAL ;
    SHAPE ABUTMENT ;
    PORT
      LAYER {layer} ;
      RECT 0.000 {y - pin_w/2:.3f} {pin_w:.3f} {y + pin_w/2:.3f} ;
    END
  END {full}
""")
            y += pitch
    # power straps (horizontal, alternating VSS/VDD), as in create_lef.py
    strap_w = pin_w * 4
    strap_pitch = pin_p * 8
    for pname, use, y0 in (("VSS", "GROUND", y_off),
                           ("VDD", "POWER", y_off + strap_pitch)):
        out.append(f"  PIN {pname}\n    DIRECTION INOUT ;\n"
                   f"    USE {use} ;\n    PORT\n      LAYER {layer} ;\n")
        ys = y0
        while ys <= h - y_off:
            out.append(f"      RECT {x_off:.3f} {ys - strap_w/2:.3f} "
                       f"{w - x_off:.3f} {ys + strap_w/2:.3f} ;\n")
            ys += strap_pitch * 2
        out.append(f"    END\n  END {pname}\n")
    # block every routing layer up to the pin layer
    out.append("  OBS\n")
    for l in range(1, int(layer.replace(prefix, "")) + 1):
        out.append(f"    LAYER {prefix}{l} ;\n    RECT 0 0 {w:.3f} {h:.3f} ;\n")
    out.append(f"  END\nEND {name}\n\nEND LIBRARY\n")
    (out_dir / f"{name}.lef").write_text("".join(out))


# ──────────────────────────────────────────────────────────────────────────
def patch_fakeram_write_bug(v_file):
    """Stock FakeRAM2.0 writes `mem[addr] <= wd | mem[addr]` (leftover of the
    commented-out write mask). Patch to a plain write for correct sim."""
    txt = v_file.read_text()
    fixed = txt.replace("mem[addr_in] <= (wd_in) | (mem[addr_in]);",
                        "mem[addr_in] <= wd_in;")
    if fixed != txt:
        v_file.write_text(fixed)
        print(f"  patched write-OR bug in {v_file.name}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    here = Path(__file__).resolve().parent
    ap.add_argument("--fakeram", type=Path, default=Path("/Users/sjia/FakeRAM2.0"))
    ap.add_argument("--out", type=Path, default=here.parent / "macros")
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)

    # 1. write the FakeRAM2.0 cfg (stock 1RW macros)
    cfg = dict(PROCESS_CFG)
    cfg["srams"] = SRAMS_1RW
    cfg_path = here / "mobol_sram.cfg"
    import json
    cfg_path.write_text(json.dumps(cfg, indent=2))
    print(f"wrote {cfg_path}")

    # 2. run stock FakeRAM2.0 for the 1RW views
    subprocess.run([sys.executable, "run.py", str(cfg_path),
                    "--output_dir", str(args.out)],
                   cwd=args.fakeram, check=True)
    for m in SRAMS_1RW:
        patch_fakeram_write_bug(args.out / m["name"] / f"{m['name']}.v")

    # 3. emit the extended 2R1W views, reusing FakeRAM2.0's process/area model
    sys.path.insert(0, str(args.fakeram))
    from utils.class_process import Process        # noqa: E402
    from utils.area import get_macro_dimensions    # noqa: E402
    proc = Process(cfg)
    for m in SRAMS_2R1W:
        h_um, w_um = get_macro_dimensions(proc, m)
        w_um *= MULTIPORT_AREA_FACTOR               # dual-copy replication
        dims = (w_um, h_um, w_um * h_um)
        d = args.out / m["name"]
        d.mkdir(parents=True, exist_ok=True)
        write_verilog_2r1w(m, d)
        write_blackbox_2r1w(m, d)
        write_lib_2r1w(m, dims, d, cfg["voltage"])
        write_lef_2r1w(m, dims, d, cfg)
        print(f"wrote 2R1W views: {d}  ({w_um:.1f} x {h_um:.1f} um, "
              f"{w_um*h_um/1e6:.3f} mm2)")


if __name__ == "__main__":
    main()
