// sram_2r1w_macro.sv — macro-backed implementation of sram_2r1w (SYNTHESIS).
//
// Drop-in replacement for the behavioral model in sram/sram_2r1w.sv: same
// module name, parameters and ports, so tile_top / tile_node need no edits.
// A synthesis file list includes THIS file; a simulation file list includes
// the behavioral one (never both — they define the same module).
//
// The macro mobol_sram_4096x512_2r1w is generated by
// synth/fakeram/gen_sram_macros.py (FakeRAM2.0 + 2R1W extension) and has
// identical timing semantics: synchronous write + synchronous 1-cycle read,
// read-during-write to the same address returns the OLD data. Equivalence is
// checked cycle-by-cycle against the behavioral model by
// synth/verif/tb_sram_equiv.cpp (make -C synth equiv).
`ifndef SRAM_2R1W_SV
`define SRAM_2R1W_SV

module sram_2r1w #(
    parameter int DATA_W = 512,           // 64 B line
    parameter int DEPTH  = (1<<18)/64,    // 256 KB / 64 B = 4096 lines
    parameter int ADDR_W = $clog2(DEPTH)
) (
    input  logic              clk,
    // write port
    input  logic              we,
    input  logic [ADDR_W-1:0] waddr,
    input  logic [DATA_W-1:0] wdata,
    // read port 0
    input  logic [ADDR_W-1:0] raddr0,
    output logic [DATA_W-1:0] rdata0,
    // read port 1
    input  logic [ADDR_W-1:0] raddr1,
    output logic [DATA_W-1:0] rdata1
);
  // The macro exists in exactly one geometry (ARCH_SPEC §3.5). Any other
  // parameterization must fail at elaboration, not silently truncate.
  generate
    if (DATA_W != 512 || DEPTH != 4096) begin : g_param_check
      unsupported_sram_2r1w_configuration u_error ();
    end
  endgenerate

  // ce_in tied high: the behavioral model reads every cycle, so must we.
  mobol_sram_4096x512_2r1w u_macro (
    .clk       (clk),
    .ce_in     (1'b1),
    .we_in     (we),
    .waddr_in  (waddr),
    .wd_in     (wdata),
    .raddr0_in (raddr0),
    .rd0_out   (rdata0),
    .raddr1_in (raddr1),
    .rd1_out   (rdata1)
  );
endmodule

`endif
